package pumpkin:plugin@0.1.0;

interface enchantments {
  enum enchantment {
    aqua-affinity,
    bane-of-arthropods,
    binding-curse,
    blast-protection,
    breach,
    channeling,
    density,
    depth-strider,
    efficiency,
    feather-falling,
    fire-aspect,
    fire-protection,
    flame,
    fortune,
    frost-walker,
    impaling,
    infinity,
    knockback,
    looting,
    loyalty,
    luck-of-the-sea,
    lunge,
    lure,
    mending,
    multishot,
    piercing,
    power,
    projectile-protection,
    protection,
    punch,
    quick-charge,
    respiration,
    riptide,
    sharpness,
    silk-touch,
    smite,
    soul-speed,
    sweeping-edge,
    swift-sneak,
    thorns,
    unbreaking,
    vanishing-curse,
    wind-burst,
  }
}
