use heck::{ToPascalCase, ToSnakeCase};
use std::{fs, path::Path};
use syn::{Fields, Item};

pub fn build_java_mapping() -> String {
    let mut output = String::new();
    output.push_str("// Generated by pumpkin-codegen. Do not edit.\n");
    output.push_str("#![allow(clippy::all)]\n");
    output.push_str("#![allow(clippy::pedantic)]\n");
    output.push_str("#![allow(unused_imports)]\n");
    output.push_str("#![allow(unused_variables)]\n");
    output.push_str("use crate::plugin::loader::wasm::wasm_host::wit::v0_1::pumpkin::plugin::java_packets::{ClientboundPacket, ServerboundPacket};\n");
    output.push_str("use pumpkin_protocol::codec::var_int::VarInt;\n");
    output.push_str("use pumpkin_util::version::JavaMinecraftVersion;\n");
    output.push_str("use bytes::Bytes;\n");
    output.push_str("use std::io::Cursor;\n");
    output.push_str("use std::any::Any;\n");
    output.push_str("use pumpkin_protocol::packet::MultiVersionJavaPacket;\n");
    output.push_str("use pumpkin_protocol::packet::Packet;\n\n");

    output.push_str("#[must_use]\n");
    output.push_str("pub fn serialize_java_packet(packet: &ClientboundPacket, version: JavaMinecraftVersion) -> Option<Bytes> {\n");
    output.push_str("    match packet {\n");

    let client_states = &["config", "login", "play", "status"];
    let server_states = &["config", "handshake", "login", "play", "status"];

    for state in client_states {
        process_packets(
            &format!("../pumpkin-protocol/src/java/client/{}", state),
            state,
            &mut output,
            "java_packet",
            "ClientboundPacket",
            &format!("pumpkin_protocol::java::client::{}", state),
            false,
            MappingMode::Serialize,
        );
    }

    output.push_str("        _ => None,\n");
    output.push_str("    }\n");
    output.push_str("}\n\n");

    output.push_str("#[must_use]\n");
    output.push_str("pub fn deserialize_java_serverbound_packet(id: i32, payload: &[u8], version: JavaMinecraftVersion) -> Option<ServerboundPacket> {\n");
    output.push_str("    match id {\n");

    for state in server_states {
        process_packets(
            &format!("../pumpkin-protocol/src/java/server/{}", state),
            state,
            &mut output,
            "java_packet",
            "ServerboundPacket",
            &format!("pumpkin_protocol::java::server::{}", state),
            false,
            MappingMode::Deserialize,
        );
    }

    output.push_str("        _ => None,\n");
    output.push_str("    }\n");
    output.push_str("}\n\n");

    output.push_str("pub trait ToWitClientboundJava {\n");
    output.push_str("    fn to_wit(&self) -> ClientboundPacket;\n");
    output.push_str("}\n\n");

    for state in client_states {
        process_packets(
            &format!("../pumpkin-protocol/src/java/client/{}", state),
            state,
            &mut output,
            "java_packet",
            "ClientboundPacket",
            &format!("pumpkin_protocol::java::client::{}", state),
            false,
            MappingMode::ToWit,
        );
    }

    output.push_str("#[must_use]\n");
    output.push_str(
        "pub fn clientbound_java_any_to_wit(any: &dyn Any) -> Option<ClientboundPacket> {\n",
    );
    for state in client_states {
        process_packets(
            &format!("../pumpkin-protocol/src/java/client/{}", state),
            state,
            &mut output,
            "java_packet",
            "ClientboundPacket",
            &format!("pumpkin_protocol::java::client::{}", state),
            false,
            MappingMode::Downcast,
        );
    }
    output.push_str("    None\n");
    output.push_str("}\n\n");

    output
}

pub fn build_bedrock_mapping() -> String {
    let mut output = String::new();
    output.push_str("\nuse crate::plugin::loader::wasm::wasm_host::wit::v0_1::pumpkin::plugin::bedrock_packets::{ClientboundPacket as BClientboundPacket, ServerboundPacket as BServerboundPacket};\n\n");
    output.push_str("#[must_use]\n");
    output.push_str(
        "pub fn serialize_bedrock_packet(packet: &BClientboundPacket) -> Option<Bytes> {\n",
    );
    output.push_str("    match packet {\n");

    process_packets(
        "../pumpkin-protocol/src/bedrock/client",
        "",
        &mut output,
        "packet",
        "BClientboundPacket",
        "pumpkin_protocol::bedrock::client",
        true,
        MappingMode::Serialize,
    );

    output.push_str("        _ => None,\n");
    output.push_str("    }\n");
    output.push_str("}\n\n");

    output.push_str("#[must_use]\n");
    output.push_str("pub fn deserialize_bedrock_serverbound_packet(id: i32, payload: &[u8]) -> Option<BServerboundPacket> {\n");
    output.push_str("    match id {\n");

    process_packets(
        "../pumpkin-protocol/src/bedrock/server",
        "",
        &mut output,
        "packet",
        "BServerboundPacket",
        "pumpkin_protocol::bedrock::server",
        true,
        MappingMode::Deserialize,
    );

    output.push_str("        _ => None,\n");
    output.push_str("    }\n");
    output.push_str("}\n\n");

    output.push_str("pub trait ToWitClientboundBedrock {\n");
    output.push_str("    fn to_wit(&self) -> BClientboundPacket;\n");
    output.push_str("}\n\n");

    process_packets(
        "../pumpkin-protocol/src/bedrock/client",
        "",
        &mut output,
        "packet",
        "BClientboundPacket",
        "pumpkin_protocol::bedrock::client",
        true,
        MappingMode::ToWit,
    );

    output.push_str("#[must_use]\n");
    output.push_str(
        "pub fn clientbound_bedrock_any_to_wit(any: &dyn Any) -> Option<BClientboundPacket> {\n",
    );
    process_packets(
        "../pumpkin-protocol/src/bedrock/client",
        "",
        &mut output,
        "packet",
        "BClientboundPacket",
        "pumpkin_protocol::bedrock::client",
        true,
        MappingMode::Downcast,
    );
    output.push_str("    None\n");
    output.push_str("}\n\n");

    output
}

#[derive(Clone, Copy, PartialEq)]
enum MappingMode {
    Serialize,
    Deserialize,
    ToWit,
    Downcast,
}

fn process_packets(
    dir: &str,
    state: &str,
    output: &mut String,
    attr_name: &str,
    variant_prefix: &str,
    rust_path_prefix: &str,
    skip_raknet: bool,
    mode: MappingMode,
) {
    let paths = fs::read_dir(dir).expect("Failed to read packet directory");
    let mut sorted_paths: Vec<_> = paths
        .map(|e| e.expect("Failed to read entry").path())
        .collect();
    sorted_paths.sort();

    for path in sorted_paths {
        if path.is_dir() {
            if skip_raknet && path.file_name().unwrap() == "raknet" {
                continue;
            }
            process_packets(
                path.to_str().unwrap(),
                state,
                output,
                attr_name,
                variant_prefix,
                rust_path_prefix,
                skip_raknet,
                mode,
            );
            continue;
        }
        if path.extension().is_some_and(|ext| ext == "rs")
            && path.file_name().is_some_and(|name| name != "mod.rs")
        {
            parse_packet_file(
                &path,
                state,
                output,
                attr_name,
                variant_prefix,
                rust_path_prefix,
                mode,
            );
        }
    }
}

fn parse_packet_file(
    path: &Path,
    state: &str,
    output: &mut String,
    attr_name: &str,
    variant_prefix: &str,
    rust_path_prefix: &str,
    mode: MappingMode,
) {
    let content = fs::read_to_string(path).expect("Failed to read file");
    let file = syn::parse_file(&content).expect("Failed to parse file");

    for item in file.items {
        if let Item::Struct(s) = item {
            if !s.attrs.iter().any(|attr| attr.path().is_ident(attr_name)) {
                continue;
            }

            let struct_name = s.ident.to_string();
            if struct_name == "CHandshake" {
                continue;
            } // Skip CHandshake (RakNet)
            let wit_case = if state == "play" || state.is_empty() {
                struct_name.to_pascal_case()
            } else {
                format!("{}{}", state.to_pascal_case(), struct_name.to_pascal_case())
            };
            let mut has_lifetime = false;
            if !s.generics.params.is_empty() {
                has_lifetime = true;
            }
            let struct_name_with_lt = if has_lifetime {
                format!("{}<'_>", struct_name)
            } else {
                struct_name.clone()
            };

            let mut prep_code = String::new();
            let mut field_inits = String::new();
            let mut possible = true;

            if let Fields::Named(fields) = s.fields {
                for field in fields.named {
                    if !matches!(field.vis, syn::Visibility::Public(_)) {
                        possible = false;
                        break;
                    }
                    let mut field_name = field.ident.as_ref().unwrap().to_string();
                    let wit_field = field_name.to_snake_case();
                    let (type_ident, is_ref, is_slice) = get_type_info(&field.ty);

                    if type_ident == "DynamicRecipe" {
                        if mode == MappingMode::Serialize {
                            field_inits
                                .push_str(&format!("                {}: &[],\n", field_name));
                        } else {
                            possible = false; // Cannot handle DynamicRecipe yet
                        }
                        continue;
                    }

                    if field_name == "type" {
                        field_name = "r#type".to_string();
                    }

                    match type_ident.as_str() {
                        "String" | "str" => {
                            if mode == MappingMode::Serialize {
                                if is_ref {
                                    field_inits.push_str(&format!(
                                        "                {}: &data.{},\n",
                                        field_name, wit_field
                                    ));
                                } else {
                                    field_inits.push_str(&format!(
                                        "                {}: data.{}.clone(),\n",
                                        field_name, wit_field
                                    ));
                                }
                            } else if mode == MappingMode::Deserialize {
                                field_inits.push_str(&format!(
                                    "                {}: p.{}.into(),\n",
                                    wit_field, field_name
                                ));
                            } else {
                                // ToWit
                                field_inits.push_str(&format!(
                                    "                {}: self.{}.to_string(),\n",
                                    wit_field, field_name
                                ));
                            }
                        }
                        "VarUInt" => {
                            if mode == MappingMode::Serialize {
                                field_inits.push_str(&format!("                {}: pumpkin_protocol::codec::var_uint::VarUInt(data.{}.try_into().unwrap()),\n", field_name, wit_field));
                            } else if mode == MappingMode::Deserialize {
                                field_inits.push_str(&format!(
                                    "                {}: p.{}.0.try_into().unwrap(),\n",
                                    wit_field, field_name
                                ));
                            } else {
                                field_inits.push_str(&format!(
                                    "                {}: self.{}.0.try_into().unwrap(),\n",
                                    wit_field, field_name
                                ));
                            }
                        }
                        "VarLong" | "VarULong" => {
                            let is_ulong = type_ident == "VarULong";
                            let path = if is_ulong {
                                "pumpkin_protocol::codec::var_ulong::VarULong"
                            } else {
                                "pumpkin_protocol::codec::var_long::VarLong"
                            };

                            if mode == MappingMode::Serialize {
                                if is_slice {
                                    prep_code.push_str(&format!(
                                        "            let vec_{}: Vec<{}> = data.{}.iter().map(|v| {}(*v as _)).collect();\n",
                                        wit_field, path, wit_field, path
                                    ));
                                    if is_ref {
                                        field_inits.push_str(&format!(
                                            "                {}: &vec_{},\n",
                                            field_name, wit_field
                                        ));
                                    } else {
                                        field_inits.push_str(&format!(
                                            "                {}: vec_{},\n",
                                            field_name, wit_field
                                        ));
                                    }
                                } else {
                                    if is_ref {
                                        prep_code.push_str(&format!(
                                            "            let var_long_{} = {}(data.{}.try_into().unwrap());\n",
                                            wit_field, path, wit_field
                                        ));
                                        field_inits.push_str(&format!(
                                            "                {}: &var_long_{},\n",
                                            field_name, wit_field
                                        ));
                                    } else {
                                        field_inits.push_str(&format!(
                                            "                {}: {}(data.{}.try_into().unwrap()),\n",
                                            field_name, path, wit_field
                                        ));
                                    }
                                }
                            } else if mode == MappingMode::Deserialize {
                                if is_slice {
                                    field_inits.push_str(&format!(
                                        "                {}: p.{}.iter().map(|v| v.0 as _).collect(),\n",
                                        wit_field, field_name
                                    ));
                                } else {
                                    field_inits.push_str(&format!(
                                        "                {}: p.{}.0.try_into().unwrap(),\n",
                                        wit_field, field_name
                                    ));
                                }
                            } else {
                                // ToWit
                                if is_slice {
                                    field_inits.push_str(&format!(
                                        "                {}: self.{}.iter().map(|v| v.0 as _).collect(),\n",
                                        wit_field, field_name
                                    ));
                                } else {
                                    field_inits.push_str(&format!(
                                        "                {}: self.{}.0.try_into().unwrap(),\n",
                                        wit_field, field_name
                                    ));
                                }
                            }
                        }
                        "TextComponent" => {
                            if mode == MappingMode::Serialize {
                                prep_code.push_str(&format!("            let component_{} = pumpkin_util::text::TextComponent::text(data.{}.clone());\n", wit_field, wit_field));
                                if is_ref {
                                    field_inits.push_str(&format!(
                                        "                {}: &component_{},\n",
                                        field_name, wit_field
                                    ));
                                } else {
                                    field_inits.push_str(&format!(
                                        "                {}: component_{},\n",
                                        field_name, wit_field
                                    ));
                                }
                            } else if mode == MappingMode::Deserialize {
                                field_inits.push_str(&format!("                {}: serde_json::to_string(&p.{}).unwrap_or_default(),\n", wit_field, field_name));
                            } else {
                                field_inits.push_str(&format!("                {}: serde_json::to_string(&self.{}).unwrap_or_default(),\n", wit_field, field_name));
                            }
                        }
                        "BlockPos" => {
                            if mode == MappingMode::Serialize {
                                field_inits.push_str(&format!("                {}: pumpkin_util::math::position::BlockPos::new(data.{}.0, data.{}.1, data.{}.2),\n", field_name, wit_field, wit_field, wit_field));
                            } else if mode == MappingMode::Deserialize {
                                field_inits.push_str(&format!(
                                    "                {}: (p.{}.0.x, p.{}.0.y, p.{}.0.z),\n",
                                    wit_field, field_name, field_name, field_name
                                ));
                            } else {
                                field_inits.push_str(&format!("                {}: (self.{}.0.x, self.{}.0.y, self.{}.0.z),\n", wit_field, field_name, field_name, field_name));
                            }
                        }
                        "Vector3" => {
                            if mode == MappingMode::Serialize {
                                field_inits.push_str(&format!("                {}: pumpkin_util::math::vector3::Vector3::new(data.{}.0 as _, data.{}.1 as _, data.{}.2 as _),\n", field_name, wit_field, wit_field, wit_field));
                            } else if mode == MappingMode::Deserialize {
                                field_inits.push_str(&format!("                {}: (p.{}.x as _, p.{}.y as _, p.{}.z as _),\n", wit_field, field_name, field_name, field_name));
                            } else {
                                field_inits.push_str(&format!("                {}: (self.{}.x as _, self.{}.y as _, self.{}.z as _),\n", wit_field, field_name, field_name, field_name));
                            }
                        }
                        "Uuid" => {
                            if mode == MappingMode::Serialize {
                                if is_slice {
                                    prep_code.push_str(&format!("            let vec_{} = data.{}.iter().map(|u| uuid::Uuid::from_u64_pair(u.high, u.low)).collect::<Vec<_>>();\n", wit_field, wit_field));
                                    if is_ref {
                                        field_inits.push_str(&format!(
                                            "                {}: &vec_{},\n",
                                            field_name, wit_field
                                        ));
                                    } else {
                                        field_inits.push_str(&format!(
                                            "                {}: vec_{},\n",
                                            field_name, wit_field
                                        ));
                                    }
                                } else {
                                    prep_code.push_str(&format!("            let uuid_{} = uuid::Uuid::from_u64_pair(data.{}.high, data.{}.low);\n", wit_field, wit_field, wit_field));
                                    if is_ref {
                                        field_inits.push_str(&format!(
                                            "                {}: &uuid_{},\n",
                                            field_name, wit_field
                                        ));
                                    } else {
                                        field_inits.push_str(&format!(
                                            "                {}: uuid_{},\n",
                                            field_name, wit_field
                                        ));
                                    }
                                }
                            } else if mode == MappingMode::Deserialize {
                                if is_slice {
                                    field_inits.push_str(&format!("                {}: p.{}.iter().map(|u| crate::plugin::loader::wasm::wasm_host::wit::v0_1::pumpkin::plugin::uuid::Uuid {{ high: u.as_u64_pair().1, low: u.as_u64_pair().0 }}).collect(),\n", wit_field, field_name));
                                } else {
                                    field_inits.push_str(&format!("                {}: crate::plugin::loader::wasm::wasm_host::wit::v0_1::pumpkin::plugin::uuid::Uuid {{ high: p.{}.as_u64_pair().1, low: p.{}.as_u64_pair().0 }},\n", wit_field, field_name, field_name));
                                }
                            } else {
                                // ToWit
                                if is_slice {
                                    field_inits.push_str(&format!("                {}: self.{}.iter().map(|u| crate::plugin::loader::wasm::wasm_host::wit::v0_1::pumpkin::plugin::uuid::Uuid {{ high: u.as_u64_pair().1, low: u.as_u64_pair().0 }}).collect(),\n", wit_field, field_name));
                                } else {
                                    field_inits.push_str(&format!("                {}: crate::plugin::loader::wasm::wasm_host::wit::v0_1::pumpkin::plugin::uuid::Uuid {{ high: self.{}.as_u64_pair().1, low: self.{}.as_u64_pair().0 }},\n", wit_field, field_name, field_name));
                                }
                            }
                        }
                        "i32" | "u32" | "i64" | "u64" | "bool" | "f32" | "f64" | "u8" | "i8"
                        | "u16" | "i16" | "VarInt" => {
                            if mode == MappingMode::Serialize {
                                if is_slice {
                                    if type_ident == "u8" {
                                        if is_ref {
                                            field_inits.push_str(&format!(
                                                "                {}: &data.{},\n",
                                                field_name, wit_field
                                            ));
                                        } else {
                                            field_inits.push_str(&format!(
                                                "                {}: data.{}.clone(),\n",
                                                field_name, wit_field
                                            ));
                                        }
                                    } else if type_ident == "VarInt" {
                                        prep_code.push_str(&format!("            let vec_{}: Vec<VarInt> = data.{}.iter().map(|v| VarInt(*v)).collect();\n", wit_field, wit_field));
                                        if is_ref {
                                            field_inits.push_str(&format!(
                                                "                {}: &vec_{},\n",
                                                field_name, wit_field
                                            ));
                                        } else {
                                            field_inits.push_str(&format!(
                                                "                {}: vec_{},\n",
                                                field_name, wit_field
                                            ));
                                        }
                                    } else {
                                        field_inits.push_str(&format!("                {}: data.{}.iter().map(|v| *v as _).collect(),\n", field_name, wit_field));
                                    }
                                } else if type_ident == "VarInt" {
                                    if is_ref {
                                        prep_code.push_str(&format!(
                                            "            let var_int_{} = VarInt(data.{});\n",
                                            wit_field, wit_field
                                        ));
                                        field_inits.push_str(&format!(
                                            "                {}: &var_int_{},\n",
                                            field_name, wit_field
                                        ));
                                    } else {
                                        field_inits.push_str(&format!(
                                            "                {}: VarInt(data.{}),\n",
                                            field_name, wit_field
                                        ));
                                    }
                                } else {
                                    if is_ref {
                                        prep_code.push_str(&format!(
                                            "            let val_{} = data.{}.try_into().unwrap();\n",
                                            wit_field, wit_field
                                        ));
                                        field_inits.push_str(&format!(
                                            "                {}: &val_{},\n",
                                            field_name, wit_field
                                        ));
                                    } else {
                                        field_inits.push_str(&format!(
                                            "                {}: data.{}.try_into().unwrap(),\n",
                                            field_name, wit_field
                                        ));
                                    }
                                }
                            } else if mode == MappingMode::Deserialize {
                                if is_slice {
                                    if type_ident == "VarInt" {
                                        field_inits.push_str(&format!("                {}: p.{}.iter().map(|v| v.0 as _).collect(),\n", wit_field, field_name));
                                    } else {
                                        field_inits.push_str(&format!("                {}: p.{}.iter().map(|v| *v as _).collect(),\n", wit_field, field_name));
                                    }
                                } else if type_ident == "VarInt" {
                                    field_inits.push_str(&format!(
                                        "                {}: p.{}.0.try_into().unwrap(),\n",
                                        wit_field, field_name
                                    ));
                                } else {
                                    field_inits.push_str(&format!(
                                        "                {}: p.{}.try_into().unwrap(),\n",
                                        wit_field, field_name
                                    ));
                                }
                            } else {
                                // ToWit
                                if is_slice {
                                    if type_ident == "VarInt" {
                                        field_inits.push_str(&format!("                {}: self.{}.iter().map(|v| v.0 as _).collect(),\n", wit_field, field_name));
                                    } else {
                                        field_inits.push_str(&format!("                {}: self.{}.iter().map(|v| *v as _).collect(),\n", wit_field, field_name));
                                    }
                                } else if type_ident == "VarInt" {
                                    field_inits.push_str(&format!(
                                        "                {}: self.{}.0.try_into().unwrap(),\n",
                                        wit_field, field_name
                                    ));
                                } else {
                                    field_inits.push_str(&format!(
                                        "                {}: self.{}.try_into().unwrap(),\n",
                                        wit_field, field_name
                                    ));
                                }
                            }
                        }
                        _ => {
                            possible = false;
                            break;
                        }
                    }
                }
            } else {
                possible = false;
            }

            if possible {
                if mode == MappingMode::Serialize {
                    output.push_str(&format!(
                        "        {}::{}(data) => {{\n",
                        variant_prefix, wit_case
                    ));
                    output.push_str(&prep_code);
                    output.push_str(&format!(
                        "            let p = {}::{} {{\n",
                        rust_path_prefix, struct_name
                    ));
                    output.push_str(&field_inits);
                    output.push_str("            };\n");
                    output.push_str("            let mut buf = Vec::new();\n");
                    if attr_name == "java_packet" {
                        output.push_str("            crate::net::java::JavaClient::write_packet_for_version(&p, version, &mut buf).unwrap();\n");
                    } else {
                        output.push_str("            crate::net::bedrock::BedrockClient::write_raw_packet(&p, &mut buf).unwrap();\n");
                    }
                    output.push_str("            Some(buf.into())\n");
                    output.push_str("        }\n");
                } else if mode == MappingMode::Deserialize {
                    if rust_path_prefix.contains("java") {
                        if rust_path_prefix.contains("client") {
                            // Skip clientbound deserialization for Java for now
                            continue;
                        }
                        output.push_str(&format!(
                            "        id if id == {}::{}::to_id(version) => {{\n",
                            rust_path_prefix, struct_name
                        ));
                        output.push_str(&format!(
                            "            use pumpkin_protocol::ServerPacket;\n"
                        ));
                        output.push_str(&format!(
                            "            let p = <{}::{} as pumpkin_protocol::ServerPacket>::read(&mut Cursor::new(payload), &version).ok()?;\n",
                            rust_path_prefix, struct_name
                        ));
                    } else {
                        if rust_path_prefix.contains("client") {
                            // Skip clientbound deserialization for Bedrock for now
                            continue;
                        }
                        output.push_str(&format!(
                            "        id if id == <{}::{} as pumpkin_protocol::Packet>::PACKET_ID as i32 => {{\n",
                            rust_path_prefix, struct_name
                        ));
                        output.push_str(&format!(
                            "            use pumpkin_protocol::BServerPacket;\n"
                        ));
                        output.push_str(&format!(
                            "            let p = <{}::{} as pumpkin_protocol::BServerPacket>::read(&mut Cursor::new(payload)).ok()?;\n",
                            rust_path_prefix, struct_name
                        ));
                    }
                    output.push_str(&prep_code);
                    output.push_str(&format!(
                        "            Some({}::{}(crate::plugin::loader::wasm::wasm_host::wit::v0_1::pumpkin::plugin::{}::{} {{\n",
                        variant_prefix, wit_case, if rust_path_prefix.contains("java") { "java_packets" } else { "bedrock_packets" }, wit_case
                    ));
                    output.push_str(&field_inits);
                    output.push_str("            }))\n");
                    output.push_str("        }\n");
                } else if mode == MappingMode::ToWit {
                    output.push_str(&format!(
                        "impl ToWitClientbound{} for {}::{} {{\n",
                        if rust_path_prefix.contains("java") {
                            "Java"
                        } else {
                            "Bedrock"
                        },
                        rust_path_prefix,
                        struct_name_with_lt
                    ));
                    output.push_str(&format!(
                        "    fn to_wit(&self) -> {} {{\n",
                        if rust_path_prefix.contains("java") {
                            "ClientboundPacket"
                        } else {
                            "BClientboundPacket"
                        }
                    ));
                    output.push_str(&prep_code);
                    output.push_str(&format!(
                        "        {}::{}(crate::plugin::loader::wasm::wasm_host::wit::v0_1::pumpkin::plugin::{}::{} {{\n",
                        variant_prefix, wit_case, if rust_path_prefix.contains("java") { "java_packets" } else { "bedrock_packets" }, wit_case
                    ));
                    output.push_str(&field_inits);
                    output.push_str("        })\n");
                    output.push_str("    }\n");
                    output.push_str("}\n\n");
                } else if mode == MappingMode::Downcast {
                    output.push_str(&format!(
                        "    if let Some(p) = any.downcast_ref::<{}::{}>() {{\n",
                        rust_path_prefix, struct_name
                    ));
                    output.push_str(&format!("        return Some(p.to_wit());\n"));
                    output.push_str("    }\n");
                }
            }
        }
    }
}

fn get_type_info(ty: &syn::Type) -> (String, bool, bool) {
    match ty {
        syn::Type::Path(tp) => (
            tp.path.segments.last().unwrap().ident.to_string(),
            false,
            false,
        ),
        syn::Type::Reference(tr) => {
            let (name, _, is_slice) = get_type_info(&tr.elem);
            (name, true, is_slice)
        }
        syn::Type::Slice(ts) => {
            let (name, _, _) = get_type_info(&ts.elem);
            (name, false, true)
        }
        _ => (String::new(), false, false),
    }
}
