interface common {
    /// Serialized text component as a postcard byte array.
    /// Deprecated: use the text-component resource from the text interface instead.
    type raw-text-component = list<u8>;
    type block-position = tuple<s32, s32, s32>;
    type position = tuple<f64, f64, f64>;

    enum named-color {
        black,
        dark-blue,
        dark-green,
        dark-aqua,
        dark-red,
        dark-purple,
        gold,
        gray,
        dark-gray,
        blue,
        green,
        aqua,
        red,
        light-purple,
        yellow,
        white,
    }

    record rgb-color {
        r: u8,
        g: u8,
        b: u8,
    }

    record argb-color {
        a: u8,
        r: u8,
        g: u8,
        b: u8,
    }

    enum locale {
        af-za,
        ar-sa,
        ast-es,
        az-az,
        ba-ru,
        bar,
        be-by,
        bg-bg,
        br-fr,
        brb,
        bs-ba,
        ca-es,
        cs-cz,
        cy-gb,
        da-dk,
        de-at,
        de-ch,
        de-de,
        el-gr,
        en-au,
        en-ca,
        en-gb,
        en-nz,
        en-pt,
        en-ud,
        en-us,
        enp,
        enws,
        eo-uy,
        es-ar,
        es-cl,
        es-ec,
        es-es,
        es-mx,
        es-uy,
        es-ve,
        esan,
        et-ee,
        eu-es,
        fa-ir,
        fi-fi,
        fil-ph,
        fo-fo,
        fr-ca,
        fr-fr,
        fra-de,
        fur-it,
        fy-nl,
        ga-ie,
        gd-gb,
        gl-es,
        haw-us,
        he-il,
        hi-in,
        hr-hr,
        hu-hu,
        hy-am,
        id-id,
        ig-ng,
        io-en,
        is-is,
        isv,
        it-it,
        ja-jp,
        jbo-en,
        ka-ge,
        kk-kz,
        kn-in,
        ko-kr,
        ksh,
        kw-gb,
        la-la,
        lb-lu,
        li-li,
        lmo,
        lo-la,
        lol-us,
        lt-lt,
        lv-lv,
        lzh,
        mk-mk,
        mn-mn,
        ms-my,
        mt-mt,
        nah,
        nds-de,
        nl-be,
        nl-nl,
        nn-no,
        no-no,
        oc-fr,
        ovd,
        pl-pl,
        pt-br,
        pt-pt,
        qya-aa,
        ro-ro,
        rpr,
        ru-ru,
        ry-ua,
        sah-sah,
        se-no,
        sk-sk,
        sl-si,
        so-so,
        sq-al,
        sr-cs,
        sr-sp,
        sv-se,
        sxu,
        szl,
        ta-in,
        th-th,
        tl-ph,
        tlh-aa,
        tok,
        tr-tr,
        tt-ru,
        uk-ua,
        val-es,
        vec-it,
        vi-vn,
        yi-de,
        yo-ng,
        zh-cn,
        zh-hk,
        zh-tw,
        zlm-arab,
    }
}
