name: Close PRs

on:
  pull_request_target:
    types: [opened, reopened]
  workflow_dispatch:

permissions:
  pull-requests: write

jobs:
  manage-prs:
    runs-on: ubuntu-slim
    steps:
      - name: "Close PR(s)"
        run: |
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            echo "${{ github.event.pull_request.number }}"
          else
            gh pr list --state open --limit 200 --json number --jq '.[].number'
          fi | while read pr; do
            if [ -n "$pr" ]; then
              echo "Closing PR #$pr"
              gh pr close $pr --comment "This repository does not accept direct pull requests. See #44 for details."
            fi
          done
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
