// Generated by pumpkin-codegen. Do not edit.
#![allow(clippy::all)]
#![allow(clippy::pedantic)]
#![allow(unused_imports)]
#![allow(unused_variables)]
use crate::plugin::loader::wasm::wasm_host::wit::v0_1::pumpkin::plugin::java_packets::ClientboundPacket;
use bytes::Bytes;
use pumpkin_protocol::codec::var_int::VarInt;
use pumpkin_util::version::JavaMinecraftVersion;

#[must_use]
pub fn serialize_java_packet(
    packet: &ClientboundPacket,
    version: JavaMinecraftVersion,
) -> Option<Bytes> {
    match packet {
        ClientboundPacket::CAcknowledgeBlockChange(data) => {
            let p = pumpkin_protocol::java::client::play::CAcknowledgeBlockChange {
                sequence_id: VarInt(data.sequence_id),
            };
            let mut buf = Vec::new();
            crate::net::java::JavaClient::write_packet_for_version(&p, version, &mut buf).unwrap();
            Some(buf.into())
        }
        ClientboundPacket::CActionBar(data) => {
            let component_action_bar =
                pumpkin_util::text::TextComponent::text(data.action_bar.clone());
            let p = pumpkin_protocol::java::client::play::CActionBar {
                action_bar: &component_action_bar,
            };
            let mut buf = Vec::new();
            crate::net::java::JavaClient::write_packet_for_version(&p, version, &mut buf).unwrap();
            Some(buf.into())
        }
        ClientboundPacket::CSetBlockDestroyStage(data) => {
            let p = pumpkin_protocol::java::client::play::CSetBlockDestroyStage {
                entity_id: VarInt(data.entity_id),
                location: pumpkin_util::math::position::BlockPos::new(
                    data.location.0,
                    data.location.1,
                    data.location.2,
                ),
                destroy_stage: data.destroy_stage.try_into().unwrap(),
            };
            let mut buf = Vec::new();
            crate::net::java::JavaClient::write_packet_for_version(&p, version, &mut buf).unwrap();
            Some(buf.into())
        }
        ClientboundPacket::CBlockEvent(data) => {
            let p = pumpkin_protocol::java::client::play::CBlockEvent {
                location: pumpkin_util::math::position::BlockPos::new(
                    data.location.0,
                    data.location.1,
                    data.location.2,
                ),
                action_id: data.action_id.try_into().unwrap(),
                action_parameter: data.action_parameter.try_into().unwrap(),
                block_type: VarInt(data.block_type),
            };
            let mut buf = Vec::new();
            crate::net::java::JavaClient::write_packet_for_version(&p, version, &mut buf).unwrap();
            Some(buf.into())
        }
        ClientboundPacket::CBlockUpdate(data) => {
            let p = pumpkin_protocol::java::client::play::CBlockUpdate {
                location: pumpkin_util::math::position::BlockPos::new(
                    data.location.0,
                    data.location.1,
                    data.location.2,
                ),
                state_id: VarInt(data.state_id),
            };
            let mut buf = Vec::new();
            crate::net::java::JavaClient::write_packet_for_version(&p, version, &mut buf).unwrap();
            Some(buf.into())
        }
        ClientboundPacket::CCenterChunk(data) => {
            let p = pumpkin_protocol::java::client::play::CCenterChunk {
                chunk_x: VarInt(data.chunk_x),
                chunk_z: VarInt(data.chunk_z),
            };
            let mut buf = Vec::new();
            crate::net::java::JavaClient::write_packet_for_version(&p, version, &mut buf).unwrap();
            Some(buf.into())
        }
        ClientboundPacket::CChangeDifficulty(data) => {
            let p = pumpkin_protocol::java::client::play::CChangeDifficulty {
                difficulty: data.difficulty.try_into().unwrap(),
                locked: data.locked.try_into().unwrap(),
            };
            let mut buf = Vec::new();
            crate::net::java::JavaClient::write_packet_for_version(&p, version, &mut buf).unwrap();
            Some(buf.into())
        }
        ClientboundPacket::CChunkBatchEnd(data) => {
            let p = pumpkin_protocol::java::client::play::CChunkBatchEnd {
                batch_size: VarInt(data.batch_size),
            };
            let mut buf = Vec::new();
            crate::net::java::JavaClient::write_packet_for_version(&p, version, &mut buf).unwrap();
            Some(buf.into())
        }
        ClientboundPacket::CClearTitle(data) => {
            let p = pumpkin_protocol::java::client::play::CClearTitle {
                reset: data.reset.try_into().unwrap(),
            };
            let mut buf = Vec::new();
            crate::net::java::JavaClient::write_packet_for_version(&p, version, &mut buf).unwrap();
            Some(buf.into())
        }
        ClientboundPacket::CCloseContainer(data) => {
            let p = pumpkin_protocol::java::client::play::CCloseContainer {
                sync_id: VarInt(data.sync_id),
            };
            let mut buf = Vec::new();
            crate::net::java::JavaClient::write_packet_for_version(&p, version, &mut buf).unwrap();
            Some(buf.into())
        }
        ClientboundPacket::CCombatDeath(data) => {
            let component_message = pumpkin_util::text::TextComponent::text(data.message.clone());
            let p = pumpkin_protocol::java::client::play::CCombatDeath {
                player_id: VarInt(data.player_id),
                message: &component_message,
            };
            let mut buf = Vec::new();
            crate::net::java::JavaClient::write_packet_for_version(&p, version, &mut buf).unwrap();
            Some(buf.into())
        }
        ClientboundPacket::CCustomPayload(data) => {
            let p = pumpkin_protocol::java::client::play::CCustomPayload {
                channel: &data.channel,
                data: &data.data,
            };
            let mut buf = Vec::new();
            crate::net::java::JavaClient::write_packet_for_version(&p, version, &mut buf).unwrap();
            Some(buf.into())
        }
        ClientboundPacket::CPlayDisconnect(data) => {
            let component_reason = pumpkin_util::text::TextComponent::text(data.reason.clone());
            let p = pumpkin_protocol::java::client::play::CPlayDisconnect {
                reason: &component_reason,
            };
            let mut buf = Vec::new();
            crate::net::java::JavaClient::write_packet_for_version(&p, version, &mut buf).unwrap();
            Some(buf.into())
        }
        ClientboundPacket::CDisplayObjective(data) => {
            let p = pumpkin_protocol::java::client::play::CDisplayObjective {
                position: VarInt(data.position),
                score_name: data.score_name.clone(),
            };
            let mut buf = Vec::new();
            crate::net::java::JavaClient::write_packet_for_version(&p, version, &mut buf).unwrap();
            Some(buf.into())
        }
        ClientboundPacket::CEntityAnimation(data) => {
            let p = pumpkin_protocol::java::client::play::CEntityAnimation {
                entity_id: VarInt(data.entity_id),
                animation: data.animation.try_into().unwrap(),
            };
            let mut buf = Vec::new();
            crate::net::java::JavaClient::write_packet_for_version(&p, version, &mut buf).unwrap();
            Some(buf.into())
        }
        ClientboundPacket::CEntityPositionSync(data) => {
            let p = pumpkin_protocol::java::client::play::CEntityPositionSync {
                entity_id: VarInt(data.entity_id),
                position: pumpkin_util::math::vector3::Vector3::new(
                    data.position.0 as _,
                    data.position.1 as _,
                    data.position.2 as _,
                ),
                delta: pumpkin_util::math::vector3::Vector3::new(
                    data.delta.0 as _,
                    data.delta.1 as _,
                    data.delta.2 as _,
                ),
                yaw: data.yaw.try_into().unwrap(),
                pitch: data.pitch.try_into().unwrap(),
                on_ground: data.on_ground.try_into().unwrap(),
            };
            let mut buf = Vec::new();
            crate::net::java::JavaClient::write_packet_for_version(&p, version, &mut buf).unwrap();
            Some(buf.into())
        }
        ClientboundPacket::CEntityStatus(data) => {
            let p = pumpkin_protocol::java::client::play::CEntityStatus {
                entity_id: data.entity_id.try_into().unwrap(),
                entity_status: data.entity_status.try_into().unwrap(),
            };
            let mut buf = Vec::new();
            crate::net::java::JavaClient::write_packet_for_version(&p, version, &mut buf).unwrap();
            Some(buf.into())
        }
        ClientboundPacket::CGameEvent(data) => {
            let p = pumpkin_protocol::java::client::play::CGameEvent {
                event: data.event.try_into().unwrap(),
                value: data.value.try_into().unwrap(),
            };
            let mut buf = Vec::new();
            crate::net::java::JavaClient::write_packet_for_version(&p, version, &mut buf).unwrap();
            Some(buf.into())
        }
        ClientboundPacket::CHeadRot(data) => {
            let p = pumpkin_protocol::java::client::play::CHeadRot {
                entity_id: VarInt(data.entity_id),
                head_yaw: data.head_yaw.try_into().unwrap(),
            };
            let mut buf = Vec::new();
            crate::net::java::JavaClient::write_packet_for_version(&p, version, &mut buf).unwrap();
            Some(buf.into())
        }
        ClientboundPacket::CHurtAnimation(data) => {
            let p = pumpkin_protocol::java::client::play::CHurtAnimation {
                entity_id: VarInt(data.entity_id),
                yaw: data.yaw.try_into().unwrap(),
            };
            let mut buf = Vec::new();
            crate::net::java::JavaClient::write_packet_for_version(&p, version, &mut buf).unwrap();
            Some(buf.into())
        }
        ClientboundPacket::CItemCooldown(data) => {
            let p = pumpkin_protocol::java::client::play::CItemCooldown {
                group: data.group.clone(),
                cooldown: VarInt(data.cooldown),
            };
            let mut buf = Vec::new();
            crate::net::java::JavaClient::write_packet_for_version(&p, version, &mut buf).unwrap();
            Some(buf.into())
        }
        ClientboundPacket::CKeepAlive(data) => {
            let p = pumpkin_protocol::java::client::play::CKeepAlive {
                keep_alive_id: data.keep_alive_id.try_into().unwrap(),
            };
            let mut buf = Vec::new();
            crate::net::java::JavaClient::write_packet_for_version(&p, version, &mut buf).unwrap();
            Some(buf.into())
        }
        ClientboundPacket::CLevelEvent(data) => {
            let p = pumpkin_protocol::java::client::play::CLevelEvent {
                event: data.event.try_into().unwrap(),
                location: pumpkin_util::math::position::BlockPos::new(
                    data.location.0,
                    data.location.1,
                    data.location.2,
                ),
                data: data.data.try_into().unwrap(),
                disable_relative_volume: data.disable_relative_volume.try_into().unwrap(),
            };
            let mut buf = Vec::new();
            crate::net::java::JavaClient::write_packet_for_version(&p, version, &mut buf).unwrap();
            Some(buf.into())
        }
        ClientboundPacket::COpenScreen(data) => {
            let component_window_title =
                pumpkin_util::text::TextComponent::text(data.window_title.clone());
            let p = pumpkin_protocol::java::client::play::COpenScreen {
                sync_id: VarInt(data.sync_id),
                window_type: VarInt(data.window_type),
                window_title: &component_window_title,
            };
            let mut buf = Vec::new();
            crate::net::java::JavaClient::write_packet_for_version(&p, version, &mut buf).unwrap();
            Some(buf.into())
        }
        ClientboundPacket::COpenSignEditor(data) => {
            let p = pumpkin_protocol::java::client::play::COpenSignEditor {
                location: pumpkin_util::math::position::BlockPos::new(
                    data.location.0,
                    data.location.1,
                    data.location.2,
                ),
                is_front_text: data.is_front_text.try_into().unwrap(),
            };
            let mut buf = Vec::new();
            crate::net::java::JavaClient::write_packet_for_version(&p, version, &mut buf).unwrap();
            Some(buf.into())
        }
        ClientboundPacket::CParticle(data) => {
            let p = pumpkin_protocol::java::client::play::CParticle {
                force_spawn: data.force_spawn.try_into().unwrap(),
                important: data.important.try_into().unwrap(),
                position: pumpkin_util::math::vector3::Vector3::new(
                    data.position.0 as _,
                    data.position.1 as _,
                    data.position.2 as _,
                ),
                offset: pumpkin_util::math::vector3::Vector3::new(
                    data.offset.0 as _,
                    data.offset.1 as _,
                    data.offset.2 as _,
                ),
                max_speed: data.max_speed.try_into().unwrap(),
                particle_count: data.particle_count.try_into().unwrap(),
                particle_id: VarInt(data.particle_id),
                data: &data.data,
            };
            let mut buf = Vec::new();
            crate::net::java::JavaClient::write_packet_for_version(&p, version, &mut buf).unwrap();
            Some(buf.into())
        }
        ClientboundPacket::CPingResponse(data) => {
            let p = pumpkin_protocol::java::client::play::CPingResponse {
                payload: data.payload.try_into().unwrap(),
            };
            let mut buf = Vec::new();
            crate::net::java::JavaClient::write_packet_for_version(&p, version, &mut buf).unwrap();
            Some(buf.into())
        }
        ClientboundPacket::CPlayerAbilities(data) => {
            let p = pumpkin_protocol::java::client::play::CPlayerAbilities {
                flags: data.flags.try_into().unwrap(),
                flying_speed: data.flying_speed.try_into().unwrap(),
                field_of_view: data.field_of_view.try_into().unwrap(),
            };
            let mut buf = Vec::new();
            crate::net::java::JavaClient::write_packet_for_version(&p, version, &mut buf).unwrap();
            Some(buf.into())
        }
        ClientboundPacket::CRemovePlayerInfo(data) => {
            let vec_players = data
                .players
                .iter()
                .map(|u| uuid::Uuid::from_u64_pair(u.high, u.low))
                .collect::<Vec<_>>();
            let p = pumpkin_protocol::java::client::play::CRemovePlayerInfo {
                players: &vec_players,
            };
            let mut buf = Vec::new();
            crate::net::java::JavaClient::write_packet_for_version(&p, version, &mut buf).unwrap();
            Some(buf.into())
        }
        ClientboundPacket::CPlayerSpawnPosition(data) => {
            let p = pumpkin_protocol::java::client::play::CPlayerSpawnPosition {
                dimension_name: data.dimension_name.clone(),
                location: pumpkin_util::math::position::BlockPos::new(
                    data.location.0,
                    data.location.1,
                    data.location.2,
                ),
                yaw: data.yaw.try_into().unwrap(),
                pitch: data.pitch.try_into().unwrap(),
            };
            let mut buf = Vec::new();
            crate::net::java::JavaClient::write_packet_for_version(&p, version, &mut buf).unwrap();
            Some(buf.into())
        }
        ClientboundPacket::CRecipeBookAdd(data) => {
            let p = pumpkin_protocol::java::client::play::CRecipeBookAdd {
                replace: data.replace.try_into().unwrap(),
                dynamic_recipes: &[],
            };
            let mut buf = Vec::new();
            crate::net::java::JavaClient::write_packet_for_version(&p, version, &mut buf).unwrap();
            Some(buf.into())
        }
        ClientboundPacket::CRecipeBookSettings(data) => {
            let p = pumpkin_protocol::java::client::play::CRecipeBookSettings {
                crafting_open: data.crafting_open.try_into().unwrap(),
                crafting_filtering: data.crafting_filtering.try_into().unwrap(),
                furnace_open: data.furnace_open.try_into().unwrap(),
                furnace_filtering: data.furnace_filtering.try_into().unwrap(),
                blast_furnace_open: data.blast_furnace_open.try_into().unwrap(),
                blast_furnace_filtering: data.blast_furnace_filtering.try_into().unwrap(),
                smoker_open: data.smoker_open.try_into().unwrap(),
                smoker_filtering: data.smoker_filtering.try_into().unwrap(),
            };
            let mut buf = Vec::new();
            crate::net::java::JavaClient::write_packet_for_version(&p, version, &mut buf).unwrap();
            Some(buf.into())
        }
        ClientboundPacket::CRemoveEntities(data) => {
            let vec_entity_ids: Vec<VarInt> = data.entity_ids.iter().map(|v| VarInt(*v)).collect();
            let p = pumpkin_protocol::java::client::play::CRemoveEntities {
                entity_ids: &vec_entity_ids,
            };
            let mut buf = Vec::new();
            crate::net::java::JavaClient::write_packet_for_version(&p, version, &mut buf).unwrap();
            Some(buf.into())
        }
        ClientboundPacket::CRemoveMobEffect(data) => {
            let p = pumpkin_protocol::java::client::play::CRemoveMobEffect {
                entity_id: VarInt(data.entity_id),
                effect_id: VarInt(data.effect_id),
            };
            let mut buf = Vec::new();
            crate::net::java::JavaClient::write_packet_for_version(&p, version, &mut buf).unwrap();
            Some(buf.into())
        }
        ClientboundPacket::CSetBorderCenter(data) => {
            let p = pumpkin_protocol::java::client::play::CSetBorderCenter {
                x: data.x.try_into().unwrap(),
                z: data.z.try_into().unwrap(),
            };
            let mut buf = Vec::new();
            crate::net::java::JavaClient::write_packet_for_version(&p, version, &mut buf).unwrap();
            Some(buf.into())
        }
        ClientboundPacket::CSetBorderSize(data) => {
            let p = pumpkin_protocol::java::client::play::CSetBorderSize {
                diameter: data.diameter.try_into().unwrap(),
            };
            let mut buf = Vec::new();
            crate::net::java::JavaClient::write_packet_for_version(&p, version, &mut buf).unwrap();
            Some(buf.into())
        }
        ClientboundPacket::CSetBorderWarningDelay(data) => {
            let p = pumpkin_protocol::java::client::play::CSetBorderWarningDelay {
                warning_time: VarInt(data.warning_time),
            };
            let mut buf = Vec::new();
            crate::net::java::JavaClient::write_packet_for_version(&p, version, &mut buf).unwrap();
            Some(buf.into())
        }
        ClientboundPacket::CSetBorderWarningDistance(data) => {
            let p = pumpkin_protocol::java::client::play::CSetBorderWarningDistance {
                warning_blocks: VarInt(data.warning_blocks),
            };
            let mut buf = Vec::new();
            crate::net::java::JavaClient::write_packet_for_version(&p, version, &mut buf).unwrap();
            Some(buf.into())
        }
        ClientboundPacket::CSetContainerProperty(data) => {
            let p = pumpkin_protocol::java::client::play::CSetContainerProperty {
                window_id: VarInt(data.window_id),
                property: data.property.try_into().unwrap(),
                value: data.value.try_into().unwrap(),
            };
            let mut buf = Vec::new();
            crate::net::java::JavaClient::write_packet_for_version(&p, version, &mut buf).unwrap();
            Some(buf.into())
        }
        ClientboundPacket::CSetExperience(data) => {
            let p = pumpkin_protocol::java::client::play::CSetExperience {
                progress: data.progress.try_into().unwrap(),
                level: VarInt(data.level),
                total_experience: VarInt(data.total_experience),
            };
            let mut buf = Vec::new();
            crate::net::java::JavaClient::write_packet_for_version(&p, version, &mut buf).unwrap();
            Some(buf.into())
        }
        ClientboundPacket::CSetHealth(data) => {
            let p = pumpkin_protocol::java::client::play::CSetHealth {
                health: data.health.try_into().unwrap(),
                food: VarInt(data.food),
                food_saturation: data.food_saturation.try_into().unwrap(),
            };
            let mut buf = Vec::new();
            crate::net::java::JavaClient::write_packet_for_version(&p, version, &mut buf).unwrap();
            Some(buf.into())
        }
        ClientboundPacket::CSetPassengers(data) => {
            let vec_passengers: Vec<VarInt> = data.passengers.iter().map(|v| VarInt(*v)).collect();
            let p = pumpkin_protocol::java::client::play::CSetPassengers {
                entity_id: VarInt(data.entity_id),
                passengers: &vec_passengers,
            };
            let mut buf = Vec::new();
            crate::net::java::JavaClient::write_packet_for_version(&p, version, &mut buf).unwrap();
            Some(buf.into())
        }
        ClientboundPacket::CTitleText(data) => {
            let component_title = pumpkin_util::text::TextComponent::text(data.title.clone());
            let p = pumpkin_protocol::java::client::play::CTitleText {
                title: &component_title,
            };
            let mut buf = Vec::new();
            crate::net::java::JavaClient::write_packet_for_version(&p, version, &mut buf).unwrap();
            Some(buf.into())
        }
        ClientboundPacket::CTitleAnimation(data) => {
            let p = pumpkin_protocol::java::client::play::CTitleAnimation {
                fade_in_ticks: data.fade_in_ticks.try_into().unwrap(),
                stay_ticks: data.stay_ticks.try_into().unwrap(),
                fade_out_ticks: data.fade_out_ticks.try_into().unwrap(),
            };
            let mut buf = Vec::new();
            crate::net::java::JavaClient::write_packet_for_version(&p, version, &mut buf).unwrap();
            Some(buf.into())
        }
        ClientboundPacket::CSubtitle(data) => {
            let component_subtitle = pumpkin_util::text::TextComponent::text(data.subtitle.clone());
            let p = pumpkin_protocol::java::client::play::CSubtitle {
                subtitle: &component_subtitle,
            };
            let mut buf = Vec::new();
            crate::net::java::JavaClient::write_packet_for_version(&p, version, &mut buf).unwrap();
            Some(buf.into())
        }
        ClientboundPacket::CSystemChatMessage(data) => {
            let component_content = pumpkin_util::text::TextComponent::text(data.content.clone());
            let p = pumpkin_protocol::java::client::play::CSystemChatMessage {
                content: &component_content,
                overlay: data.overlay.try_into().unwrap(),
            };
            let mut buf = Vec::new();
            crate::net::java::JavaClient::write_packet_for_version(&p, version, &mut buf).unwrap();
            Some(buf.into())
        }
        ClientboundPacket::CTabList(data) => {
            let component_header = pumpkin_util::text::TextComponent::text(data.header.clone());
            let component_footer = pumpkin_util::text::TextComponent::text(data.footer.clone());
            let p = pumpkin_protocol::java::client::play::CTabList {
                header: &component_header,
                footer: &component_footer,
            };
            let mut buf = Vec::new();
            crate::net::java::JavaClient::write_packet_for_version(&p, version, &mut buf).unwrap();
            Some(buf.into())
        }
        ClientboundPacket::CTakeItemEntity(data) => {
            let p = pumpkin_protocol::java::client::play::CTakeItemEntity {
                entity_id: VarInt(data.entity_id),
                collector_entity_id: VarInt(data.collector_entity_id),
                stack_amount: VarInt(data.stack_amount),
            };
            let mut buf = Vec::new();
            crate::net::java::JavaClient::write_packet_for_version(&p, version, &mut buf).unwrap();
            Some(buf.into())
        }
        ClientboundPacket::CTickingState(data) => {
            let p = pumpkin_protocol::java::client::play::CTickingState {
                tick_rate: data.tick_rate.try_into().unwrap(),
                is_frozen: data.is_frozen.try_into().unwrap(),
            };
            let mut buf = Vec::new();
            crate::net::java::JavaClient::write_packet_for_version(&p, version, &mut buf).unwrap();
            Some(buf.into())
        }
        ClientboundPacket::CTickingStep(data) => {
            let p = pumpkin_protocol::java::client::play::CTickingStep {
                tick_steps: VarInt(data.tick_steps),
            };
            let mut buf = Vec::new();
            crate::net::java::JavaClient::write_packet_for_version(&p, version, &mut buf).unwrap();
            Some(buf.into())
        }
        ClientboundPacket::CTransfer(data) => {
            let p = pumpkin_protocol::java::client::play::CTransfer {
                host: &data.host,
                port: VarInt(data.port),
            };
            let mut buf = Vec::new();
            crate::net::java::JavaClient::write_packet_for_version(&p, version, &mut buf).unwrap();
            Some(buf.into())
        }
        ClientboundPacket::CUnloadChunk(data) => {
            let p = pumpkin_protocol::java::client::play::CUnloadChunk {
                z: data.z.try_into().unwrap(),
                x: data.x.try_into().unwrap(),
            };
            let mut buf = Vec::new();
            crate::net::java::JavaClient::write_packet_for_version(&p, version, &mut buf).unwrap();
            Some(buf.into())
        }
        ClientboundPacket::CUpdateEntityPos(data) => {
            let p = pumpkin_protocol::java::client::play::CUpdateEntityPos {
                entity_id: VarInt(data.entity_id),
                delta: pumpkin_util::math::vector3::Vector3::new(
                    data.delta.0 as _,
                    data.delta.1 as _,
                    data.delta.2 as _,
                ),
                on_ground: data.on_ground.try_into().unwrap(),
            };
            let mut buf = Vec::new();
            crate::net::java::JavaClient::write_packet_for_version(&p, version, &mut buf).unwrap();
            Some(buf.into())
        }
        ClientboundPacket::CUpdateEntityPosRot(data) => {
            let p = pumpkin_protocol::java::client::play::CUpdateEntityPosRot {
                entity_id: VarInt(data.entity_id),
                delta: pumpkin_util::math::vector3::Vector3::new(
                    data.delta.0 as _,
                    data.delta.1 as _,
                    data.delta.2 as _,
                ),
                yaw: data.yaw.try_into().unwrap(),
                pitch: data.pitch.try_into().unwrap(),
                on_ground: data.on_ground.try_into().unwrap(),
            };
            let mut buf = Vec::new();
            crate::net::java::JavaClient::write_packet_for_version(&p, version, &mut buf).unwrap();
            Some(buf.into())
        }
        ClientboundPacket::CUpdateEntityRot(data) => {
            let p = pumpkin_protocol::java::client::play::CUpdateEntityRot {
                entity_id: VarInt(data.entity_id),
                yaw: data.yaw.try_into().unwrap(),
                pitch: data.pitch.try_into().unwrap(),
                on_ground: data.on_ground.try_into().unwrap(),
            };
            let mut buf = Vec::new();
            crate::net::java::JavaClient::write_packet_for_version(&p, version, &mut buf).unwrap();
            Some(buf.into())
        }
        ClientboundPacket::CUpdateMobEffect(data) => {
            let p = pumpkin_protocol::java::client::play::CUpdateMobEffect {
                entity_id: VarInt(data.entity_id),
                effect_id: VarInt(data.effect_id),
                amplifier: VarInt(data.amplifier),
                duration: VarInt(data.duration),
                flags: data.flags.try_into().unwrap(),
            };
            let mut buf = Vec::new();
            crate::net::java::JavaClient::write_packet_for_version(&p, version, &mut buf).unwrap();
            Some(buf.into())
        }
        ClientboundPacket::CWorldEvent(data) => {
            let p = pumpkin_protocol::java::client::play::CWorldEvent {
                event: data.event.try_into().unwrap(),
                location: pumpkin_util::math::position::BlockPos::new(
                    data.location.0,
                    data.location.1,
                    data.location.2,
                ),
                data: data.data.try_into().unwrap(),
                disable_relative_volume: data.disable_relative_volume.try_into().unwrap(),
            };
            let mut buf = Vec::new();
            crate::net::java::JavaClient::write_packet_for_version(&p, version, &mut buf).unwrap();
            Some(buf.into())
        }
        _ => None,
    }
}

use crate::plugin::loader::wasm::wasm_host::wit::v0_1::pumpkin::plugin::bedrock_packets::ClientboundPacket as BClientboundPacket;

#[must_use]
pub fn serialize_bedrock_packet(packet: &BClientboundPacket) -> Option<Bytes> {
    match packet {
        BClientboundPacket::CChunkRadiusUpdate(data) => {
            let p = pumpkin_protocol::bedrock::client::CChunkRadiusUpdate {
                chunk_radius: VarInt(data.chunk_radius),
            };
            let mut buf = Vec::new();
            crate::net::bedrock::BedrockClient::write_raw_packet(&p, &mut buf).unwrap();
            Some(buf.into())
        }
        BClientboundPacket::CDisconnectPlayer(data) => {
            let p = pumpkin_protocol::bedrock::client::CDisconnectPlayer {
                reason: VarInt(data.reason),
                skip_message: data.skip_message.try_into().unwrap(),
                message: data.message.clone(),
                filtered_message: data.filtered_message.clone(),
            };
            let mut buf = Vec::new();
            crate::net::bedrock::BedrockClient::write_raw_packet(&p, &mut buf).unwrap();
            Some(buf.into())
        }
        BClientboundPacket::CLevelEvent(data) => {
            let p = pumpkin_protocol::bedrock::client::CLevelEvent {
                event_id: VarInt(data.event_id),
                position: pumpkin_util::math::vector3::Vector3::new(
                    data.position.0 as _,
                    data.position.1 as _,
                    data.position.2 as _,
                ),
                data: VarInt(data.data),
            };
            let mut buf = Vec::new();
            crate::net::bedrock::BedrockClient::write_raw_packet(&p, &mut buf).unwrap();
            Some(buf.into())
        }
        BClientboundPacket::CModalFormRequest(data) => {
            let p = pumpkin_protocol::bedrock::client::CModalFormRequest {
                form_id: VarInt(data.form_id),
                form_data: data.form_data.clone(),
            };
            let mut buf = Vec::new();
            crate::net::bedrock::BedrockClient::write_raw_packet(&p, &mut buf).unwrap();
            Some(buf.into())
        }
        BClientboundPacket::CNetworkSettings(data) => {
            let p = pumpkin_protocol::bedrock::client::CNetworkSettings {
                compression_threshold: data.compression_threshold.try_into().unwrap(),
                compression_method: data.compression_method.try_into().unwrap(),
                client_throttle_enabled: data.client_throttle_enabled.try_into().unwrap(),
                client_throttle_threshold: data.client_throttle_threshold.try_into().unwrap(),
                client_throttle_scalar: data.client_throttle_scalar.try_into().unwrap(),
            };
            let mut buf = Vec::new();
            crate::net::bedrock::BedrockClient::write_raw_packet(&p, &mut buf).unwrap();
            Some(buf.into())
        }
        BClientboundPacket::CPlayerHotbar(data) => {
            let p = pumpkin_protocol::bedrock::client::CPlayerHotbar {
                selected_slot: pumpkin_protocol::codec::var_uint::VarUInt(
                    data.selected_slot.try_into().unwrap(),
                ),
                container_id: data.container_id.try_into().unwrap(),
                should_select_block: data.should_select_block.try_into().unwrap(),
            };
            let mut buf = Vec::new();
            crate::net::bedrock::BedrockClient::write_raw_packet(&p, &mut buf).unwrap();
            Some(buf.into())
        }
        BClientboundPacket::CSetDisplayObjective(data) => {
            let p = pumpkin_protocol::bedrock::client::CSetDisplayObjective {
                display_slot: data.display_slot.clone(),
                objective_name: data.objective_name.clone(),
                display_name: data.display_name.clone(),
                criteria_name: data.criteria_name.clone(),
                sort_order: VarInt(data.sort_order),
            };
            let mut buf = Vec::new();
            crate::net::bedrock::BedrockClient::write_raw_packet(&p, &mut buf).unwrap();
            Some(buf.into())
        }
        BClientboundPacket::CRemoveObjective(data) => {
            let p = pumpkin_protocol::bedrock::client::CRemoveObjective {
                objective_name: data.objective_name.clone(),
            };
            let mut buf = Vec::new();
            crate::net::bedrock::BedrockClient::write_raw_packet(&p, &mut buf).unwrap();
            Some(buf.into())
        }
        BClientboundPacket::CSetHealth(data) => {
            let p = pumpkin_protocol::bedrock::client::CSetHealth {
                health: VarInt(data.health),
            };
            let mut buf = Vec::new();
            crate::net::bedrock::BedrockClient::write_raw_packet(&p, &mut buf).unwrap();
            Some(buf.into())
        }
        BClientboundPacket::CSetTime(data) => {
            let p = pumpkin_protocol::bedrock::client::CSetTime {
                time: VarInt(data.time),
            };
            let mut buf = Vec::new();
            crate::net::bedrock::BedrockClient::write_raw_packet(&p, &mut buf).unwrap();
            Some(buf.into())
        }
        BClientboundPacket::CSetTitle(data) => {
            let p = pumpkin_protocol::bedrock::client::CSetTitle {
                action_type: VarInt(data.action_type),
                text: data.text.clone(),
                fade_in_duration: VarInt(data.fade_in_duration),
                remain_duration: VarInt(data.remain_duration),
                fade_out_duration: VarInt(data.fade_out_duration),
                xuid: data.xuid.clone(),
                platform_online_id: data.platform_online_id.clone(),
                filtered_message: data.filtered_message.clone(),
            };
            let mut buf = Vec::new();
            crate::net::bedrock::BedrockClient::write_raw_packet(&p, &mut buf).unwrap();
            Some(buf.into())
        }
        BClientboundPacket::CTransfer(data) => {
            let p = pumpkin_protocol::bedrock::client::CTransfer {
                address: data.address.clone(),
                port: data.port.try_into().unwrap(),
                reload_world: data.reload_world.try_into().unwrap(),
            };
            let mut buf = Vec::new();
            crate::net::bedrock::BedrockClient::write_raw_packet(&p, &mut buf).unwrap();
            Some(buf.into())
        }
        _ => None,
    }
}
